# Generated by Django 6.0.5 on 2026-05-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(default="medium", max_length=20),
        ),
    ]
